# Generated by Django 5.0.3 on 2026-04-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mine_site_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('mine_site_name', models.CharField(db_index=True, max_length=200)),
                ('country_iso2', models.CharField(default='TZ', max_length=2)),
                ('national_id', models.CharField(db_index=True, max_length=50)),
                ('certification_status', models.CharField(choices=[('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green'), ('Yellow', 'Yellow')], db_index=True, max_length=20)),
                ('activity_status', models.CharField(choices=[('Active', 'Active'), ('Non-active', 'Non-active')], db_index=True, max_length=20)),
                ('primary_mineral_hs_code', models.CharField(db_index=True, max_length=20)),
                ('additional_minerals_hs_codes', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('polygon_geojson', models.TextField(blank=True, null=True)),
                ('admin1', models.CharField(db_index=True, max_length=50)),
                ('admin2', models.CharField(db_index=True, max_length=50)),
                ('license_id', models.CharField(db_index=True, max_length=50)),
                ('license_type', models.CharField(choices=[('other', 'Other'), ('artisanal_permit', 'Artisanal Permit'), ('claim', 'Claim'), ('exploration_permit', 'Exploration Permit'), ('unlicensed', 'Unlicensed'), ('mining_license', 'Mining License')], db_index=True, max_length=50)),
                ('owner_company_id', models.CharField(db_index=True, max_length=50)),
                ('operator_company_id', models.CharField(db_index=True, max_length=50)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['mine_site_name', 'certification_status'], name='api_mine_mine_si_59db9f_idx'), models.Index(fields=['admin1', 'admin2'], name='api_mine_admin1_b83743_idx')],
            },
        ),
    ]
